---
# tasks file for ansible-sysstat

- block:
    - name: Install sysstat packages
      become: yes
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: "{{ apt_cache_valid_time | default(omit) }}"
        install_recommends: no
      with_items:
        - "{{ sysstat_packages }}"

    - name: copy sysstat default configuration
      template:
        src: default_sysstat.j2
        dest: /etc/default/sysstat
        backup: no
        mode: "0644"
        
  become: yes
  tags:
    - sysstat
